name: hotel_database
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  awesome_dialog: ^3.1.0
  cached_network_image: ^3.2.3
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.3+1
  supabase_flutter: ^1.10.14
  syncfusion_flutter_datepicker: ^22.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
